# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build and Push "node" Docker image
      - name: Build and Push "node" Docker image
        run: |
          cd node
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nosqldb-node:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nosqldb-node:latest

      # Build and Push "bootstrap-server" Docker image
      - name: Build and Push "bootstrap-server" Docker image
        run: |
          cd bootstrap-server
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nosqldb-bootstrap:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nosqldb-bootstrap:latest
